#define REPONAME "foobar"
#define REPOPATH "/var/lib/darcs/repos/foobar"
#define BACKGROUND "#FFFFFF"
#define FOREGROUND "#000000"
#define FONT "Verdana, Helvetica"
#define BORDER "#000000"
#define HEADING "#AAAAFF"
#define DARCSLOG "darcs-log"
#define OUTPUT "foobar.html"
