/*
 *  output.c
 * 
 *  Copyright (c) 2005 by Miklos Vajna <vmiklos@frugalware.org>
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
 *  USA.
 */

#include <stdio.h>
#include "config.h"
#include "list.h"
#include "darcsstats.h"

void print_header(FILE* fp, char *reponame)
{
	fprintf(fp, "<html>\n");
	fprintf(fp, "<head>\n<title>%s darcs statistics</title>\n</head>\n",
		reponame);
	fprintf(fp, "<body bgcolor=\"%s\">\n", BACKGROUND);
	fprintf(fp, "<font color=\"%s\" face=\"%s\">\n", FOREGROUND, FONT);
	fprintf(fp, "<table><tr bgcolor=\"%s\"><td align=\"center\">\n",
		BACKGROUND);
	fprintf(fp, "<strong>%s darcs statistics</strong>\n", reponame);
	fprintf(fp, "</td></tr><tr><td>\n");
}

void print_footer(FILE* fp, char *reponame)
{
	fprintf(fp, "</td>\n</tr>\n<tr bgcolor=\"%s\">\n<td align=\"center\">",
		BACKGROUND);
	fprintf(fp, "<strong>%s darcs statistics generated by "
		"<b>darcsstats</b></strong><br>\n", reponame);
	fprintf(fp, "These statistics are provided purely for interested\n"
		"developers, and are not intended to reflect quality - or -\n"
		"quality of work done by any given developer in darcs, merely\n"
		"to show activity of operations in the darcs repository\n"
		"performed by all developers.  If you want to use them to \n"
		"motivate yourself, that's fine, but keep in mind that a bit\n"
		"of useful work is more meaningful than a lot of useless\n"
		"work.<br>\nCreated by "
		"<a href=\"http://frugalware.org/~vmiklos/\">Miklos Vajna</a>\n"
		"</td></tr></table></font>");
	fprintf(fp, "</body></html>");
}

void print_table(FILE* fp, DSList *list, int alllines)
{
	DSList *lp;

	fprintf(fp, "<table bgcolor=\"%s\" border=\"0\" cellspacing=\"1\" "
		"cellpadding=\"2\" width=\"100%%\">\n", BORDER);
	fprintf(fp, "<tr bgcolor=\"%s\">\n", HEADING);
	fprintf(fp, "<td>Committer</td>\n"
		"<td># of Changes</td>"
		"<td>Lines Changed</td>"
		"<td>Lines per Change</td>"
		"<td>%% of Changed Lines</td>"
		"</tr>");
	for(lp = list; lp; lp = lp->next) {
		fprintf(fp, "<tr bgcolor=\"%s\">\n", BACKGROUND);
		fprintf(fp, "<td>%s</td>\n", ((patch_t*)lp->data)->author);
		fprintf(fp, "<td>%d</td>\n", ((patch_t*)lp->data)->changes);
		fprintf(fp, "<td>%d</td>\n", ((patch_t*)lp->data)->lines);
		fprintf(fp, "<td>%d</td>\n", ((patch_t*)lp->data)->lines/
			((patch_t*)lp->data)->changes);
		fprintf(fp, "<td>%d</td>\n", 100*((patch_t*)lp->data)->lines/
			alllines);
		fprintf(fp, "<tr>\n");
	}
	fprintf(fp, "</table>\n");
}

void print_stats(FILE* fp, DSList *patches, DSList *files, file_t *highfile)
{
	DSList *lp;
	int allpatches=0;
	for(lp = patches; lp; lp = lp->next)
		allpatches += ((patch_t*)lp->data)->changes;
	fprintf(fp, "<table bgcolor=\"%s\" cellspacing=\"1\" "
		"cellpadding=\"2\" width=\"100%%\">", FOREGROUND);
	fprintf(fp, "<tr>\n<td bgcolor=\"%s\">Total authors:</td>\n", HEADING);
	fprintf(fp, "<td align=\"right\" bgcolor=\"%s\">%d</td></tr>\n",
		BACKGROUND, list_count(patches));
	fprintf(fp, "<tr>\n<td bgcolor=\"%s\">Total patches:</td>\n", HEADING);
	fprintf(fp, "<td align=\"right\" bgcolor=\"%s\">%d</td></tr>\n",
		BACKGROUND, allpatches);
	fprintf(fp, "<tr>\n<td bgcolor=\"%s\">"
		"Most frequently modified file:</td>\n", HEADING);
	fprintf(fp, "<td align=\"right\" bgcolor=\"%s\">%s (%d hunks)"
		"</td></tr>\n", BACKGROUND, highfile->name, highfile->changes);
	fprintf(fp, "</table>\n");
}
